Cargo.toml, examples/disc.rs, examples/simple.rs, src/service.rs, src/session.rs, tests/test_dial.rs
=> Add integration test

discovery/src/substream.rs, examples/disc.rs, examples/simple.rs, src/builder.rs, src/context.rs, src/lib.rs, src/service.rs, src/session.rs, src/substream.rs, src/traits.rs, src/utils.rs, tests/test_dial.rs
1. Organize module layout(Refactor)
2. Fix discovery bug(Did not tell listener, client address)
3. Add control API for service
4. Fix proto close bug(Did not clean up the corresponding data)
5. Modify the service context API
6. Fix dial not timely bug
=> Refactor modules

Cargo.toml, tests/test_kill.rs
=> add test for kill process

yamux/src/stream.rs
If send data > window size, doesn't work.
The task of window size is to limit the flow, not refusing work, so fix it, add the write buffer.
It should have a test?
=> Fix yamux bug

.gitignore, secio/Cargo.toml, secio/benches/bench.rs, secio/src/codec/mod.rs, secio/src/codec/secure_stream.rs, secio/src/lib.rs, secio/src/stream_cipher.rs
=> Add bench for secio

src/service.rs, src/session.rs
Clearly close the event flow process of the session.
old: 
service shutdown doesn't care about the session's protocol substream, session shutdown doesn't care substream.
now:
service -> session -> substream, and then service <- session <- substream
if all substream close, session close and notify service shutdown event
=> Refactor close session

secio/src/codec/secure_stream.rs, src/service.rs, tests/test_dial.rs
=> Fix undefined behavior

yamux/src/session.rs
=> Fix error handle

src/service.rs, src/session.rs, src/substream.rs, tests/test_dial.rs
=> Output codec error

secio/src/codec/secure_stream.rs, src/service.rs, src/session.rs, src/substream.rs, yamux/src/stream.rs
1. Add notify to all stream struct
2. Fix error handle on all channel try send
=> Add notify to all stream struct

secio/Cargo.toml, secio/src/handshake/handshake_struct.rs, secio/src/lib.rs, secio/src/peer_id.rs
=> Implement peer id

src/error.rs, src/lib.rs, src/service.rs, src/utils.rs, tests/test_peer_id.rs
Verify `PeerId` when dialing remote
=> Verify `PeerId` when dialing remote

secio/src/codec/secure_stream.rs, secio/src/handshake/procedure.rs, src/context.rs, src/lib.rs, src/protocol_handle_stream.rs, src/service.rs, src/session.rs, src/substream.rs
1. Separation protocol handles;
2. Tiled nested hash table;
3. Optimize partial functions
=> Optimize performance

bench/src/lib.rs, tests/test_kill.rs
=> Add median to bench output

Cargo.toml, bench/src/main.rs, examples/disc.rs, examples/ping.rs, examples/simple.rs, src/protocol_handle_stream.rs, src/service.rs, tests/test_dial.rs, tests/test_disconnect.rs, tests/test_kill.rs
Change dial api, may panic on parser fail
=> Change dial api

Cargo.toml, bench/src/main.rs, examples/disc.rs, examples/ping.rs, examples/simple.rs, src/context.rs, src/error.rs, src/service.rs, src/session.rs, src/utils.rs, src/utils/dns.rs, tests/test_dial.rs, tests/test_disconnect.rs, tests/test_kill.rs, tests/test_peer_id.rs
=> Support DNS resolver

src/protocol_select/mod.rs, src/service.rs, src/session.rs, src/substream.rs
1. Fix typo on `protocol_message` function
2. Fix missing data buffer during protocol selection
=> Fix two bugs

secio/src/codec/secure_stream.rs, secio/src/codec/stream_handle.rs, src/service.rs, src/session.rs, src/substream.rs, yamux/src/error.rs, yamux/src/session.rs, yamux/src/stream.rs
Safely close the connection and brush out all the buffers
=> Safe close session

bench/src/main.rs, discovery/src/substream.rs, examples/simple.rs, ping/src/lib.rs, secio/src/codec/stream_handle.rs, src/context.rs, tests/test_kill.rs
=> Change API

src/service.rs, src/utils.rs, src/utils/dns.rs
=> Change Result to Option

examples/disc.rs, examples/simple.rs, ping/src/lib.rs, src/context.rs, src/protocol_handle_stream.rs, src/service.rs, tests/test_dial.rs, tests/test_kill.rs
Change server context API, return `Result` is not friendly to the user, the processing will be relatively troublesome
=> Change server context API

docs/introduction_en.md
Translated from the Chinese version of the introduction.
=> Create Introduction in English

src/context.rs, src/protocol_handle_stream.rs, src/service.rs
=> Reuse structure

Cargo.toml, README.md, bench/Cargo.toml, bench/src/main.rs, discovery/Cargo.toml, discovery/src/substream.rs, examples/disc.rs, examples/ping.rs, examples/simple.rs, ping/Cargo.toml, ping/src/lib.rs, secio/Cargo.toml, secio/examples/secio_simple.rs, secio/src/peer_id.rs, src/builder.rs, src/context.rs, src/error.rs, src/lib.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/control.rs, src/session.rs, src/substream.rs, src/utils.rs, src/utils/dns.rs, tests/test_dial.rs, tests/test_disconnect.rs, tests/test_kill.rs, tests/test_peer_id.rs
=> Release 0.1

README.md, bench/src/main.rs, src/traits.rs, tests/test_dial.rs, tests/test_disconnect.rs, tests/test_kill.rs, tests/test_peer_id.rs
=> Rename empty to neither

Cargo.toml, bench/src/main.rs, examples/disc.rs, examples/ping.rs, examples/simple.rs, ping/Cargo.toml, ping/src/lib.rs, src/builder.rs, src/service.rs, src/service/config.rs, src/session.rs, src/traits.rs, tests/test_dial.rs, tests/test_disconnect.rs, tests/test_kill.rs, tests/test_peer_id.rs
=> Change meta to struct

src/context.rs, src/service.rs
=> Add keypair API

secio/src/peer_id.rs
=> Add PeerId::random()

protocols/discovery/src/lib.rs, protocols/discovery/src/substream.rs, src/context.rs, src/service.rs, src/session.rs, tests/test_dial.rs
=> Change session type

secio/src/handshake/handshake_struct.rs, src/context.rs, src/protocol_select/mod.rs, src/service.rs, src/service/event.rs, src/session.rs, src/substream.rs, yamux/Cargo.toml, yamux/src/frame.rs, yamux/src/session.rs
1. Fix session close
2. Add a test to `yamux` codec
3. Add some derive trait to struct
4. Use `with_capacity` to reduce the number of times malloc
5. Change return type to slice
=> Fix session close

src/session.rs, src/substream.rs
=> Refactor substream

protocols/discovery/src/substream.rs, secio/src/codec/secure_stream.rs, src/context.rs, src/error.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/control.rs, src/service/event.rs, src/session.rs, src/substream.rs, src/transports/mod.rs, yamux/src/stream.rs
Change the user interface to unbound to enhance the user experience.
=> Replace task channel to unbound

src/service.rs, src/session.rs, yamux/src/session.rs
=> fix: shrink vecdeque when need

bench/src/main.rs, examples/disc.rs, examples/id.rs, examples/ping.rs, src/builder.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/config.rs, tests/test_dial.rs, tests/test_kill.rs
add reopen panic handle option
=> feat: add reopen panic handle option

examples/disc.rs, protocols/discovery/src/addr.rs, protocols/discovery/src/lib.rs, protocols/discovery/src/substream.rs
=> refactor: refactor discovery

src/service.rs
fix set notify on event output
=> fix: set notify on event output

Cargo.toml, src/service.rs
=> fix: Missing notify handler

src/service.rs, src/session.rs, yamux/src/session.rs
1. When the network conditions are extremely bad, `yamux` can't always notify, which will lead to fake loop, Cpu will take up too much
2. Guarantee the order in which messages are sent
=> fix: notify on yamux

bench/src/main.rs, examples/disc.rs, examples/id.rs, examples/ping.rs, src/builder.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/config.rs, tests/test_dial.rs, tests/test_kill.rs
revert service FnMut to FnOnce
=> revert: revert service FnMut to FnOnce

Cargo.toml, protocols/discovery/Cargo.toml, protocols/identify/Cargo.toml, protocols/ping/Cargo.toml, yamux/Cargo.toml
=> chore: bump to alpha.6

secio/Cargo.toml, secio/src/codec/secure_stream.rs
1. Fix CPU usage problem of `secio` under bad network conditions
2. Deleting useless copy operation when `secio` decode (for performance)
=> fix: notify on secio

Cargo.toml, src/service/future_task.rs
=> chore: bump to alpha 8

Cargo.toml, examples/disc.rs, protocols/discovery/Cargo.toml, protocols/identify/Cargo.toml, protocols/ping/Cargo.toml, secio/Cargo.toml
=> chore: bump to alpha 9

.travis.yml, Makefile, src/context.rs, src/service.rs, src/service/control.rs, src/service/event.rs, src/service/future_task.rs, src/session.rs, src/substream.rs, tests/test_priority.rs
Implement task priority in the framework.
Let high priority messages be sent out as quickly as possible
=> feat(priority): Implement task priority in the framework

secio/src/codec/secure_stream.rs, secio/src/handshake/mod.rs, secio/src/handshake/procedure.rs, src/builder.rs, src/service.rs, src/session.rs, src/substream.rs, tests/test_priority.rs, yamux/src/config.rs, yamux/src/session.rs
When the network pressure is high, if you do not limit the buffer size, it will lead to OOM.
=> feat: add buffer size feature

examples/block_send.rs, examples/simple.rs, protocols/identify/src/lib.rs, protocols/ping/src/lib.rs, secio/src/codec/secure_stream.rs, src/context.rs, src/service.rs, src/service/control.rs, src/session.rs, src/substream.rs, tests/test_block_send.rs, tests/test_close.rs, tests/test_dial.rs, tests/test_disconnect.rs, tests/test_kill.rs, tests/test_peer_id.rs, tests/test_priority.rs, yamux/src/session.rs, yamux/src/stream.rs
The semantics of `poll_complete` function is not the same as other futures. Be careful.
=> fix: poll complete

Cargo.toml, secio/Cargo.toml, yamux/Cargo.toml
=> chore: bump to alpha 10

Cargo.toml, examples/heavy_task_schedule.rs, src/builder.rs, src/context.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/config.rs, src/service/control.rs, src/session.rs, src/substream.rs
fix blocking, bump to alpha 11
=> fix: fix blocking, bump to alpha 11

Cargo.toml, examples/heavy_task_schedule.rs, secio/Cargo.toml, secio/src/codec/secure_stream.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/control.rs, src/service/future_task.rs, src/session.rs, src/substream.rs, tests/test_block_send.rs, yamux/Cargo.toml, yamux/src/session.rs, yamux/src/stream.rs
* Improve task schedule
* Increase sender buffer size
=> perf: Improve task schedule and increase sender buffer size

examples/block_send.rs, examples/heavy_task_schedule.rs, examples/simple.rs, protocols/discovery/src/lib.rs, protocols/discovery/src/substream.rs, protocols/identify/src/lib.rs, protocols/ping/src/lib.rs, secio/src/codec/secure_stream.rs, secio/src/handshake/mod.rs, secio/src/handshake/procedure.rs, src/context.rs, src/service.rs, src/service/control.rs, src/session.rs, src/substream.rs, tests/test_block_send.rs, tests/test_close.rs, tests/test_dial.rs, tests/test_kill.rs, tests/test_priority.rs, yamux/src/config.rs, yamux/src/session.rs
=> Refactor p2p layer

Cargo.toml, protocols/discovery/Cargo.toml, protocols/identify/Cargo.toml, protocols/ping/Cargo.toml, secio/Cargo.toml, yamux/Cargo.toml
=> chore: bump to alpha 13

src/context.rs, src/protocol_handle_stream.rs, src/service.rs, src/service/event.rs
move notify to protocol stream, heavy task bug
=> fix: move notify to protocol stream, heavy task bug

Cargo.toml
=> chore: bump to  alpha 14

src/service.rs, src/session.rs, src/substream.rs, tests/test_block_send.rs
=> fix: session/substream closed

src/service.rs, src/session.rs, tests/test_block_send.rs
1. Fix session protocol open
2. Add test for session protocol
3. Others test is the same as the service protocol, so don't change them
4. Use future manager to handshake
=> fix: session protocol open

Cargo.toml, yamux/Cargo.toml
=> chore: bump to alpha 16

Cargo.toml, src/service.rs, src/service/future_task.rs, src/substream.rs, tests/test_block_future_task.rs
1. future task loop forever
2. bump to alpha 17
=> fix: future task loop forever, bump to alpha 17

src/error.rs, src/service.rs, src/service/control.rs, src/session.rs
=> chore: remove unused memory

src/service.rs, src/session.rs, tests/test_protocol_open.rs
Fix bug on protocol open command send by control
=> fix: fix bug on protocol open command send by control

src/context.rs, src/service.rs, src/service/config.rs, src/service/control.rs, src/service/event.rs
Add open protocols interface
`DialProtocol` will be deprecated on 0.3, naming is always the biggest problem(I resisted the impulse of break change)
=> feat: add open protocols interface

CHANGELOG.md, Cargo.toml, protocols/identify/Cargo.toml
=> chore: bump to 0.2.1

src/utils/dns.rs
allow dns resolver on current thread runtime
=> fix: allow dns resolver on current thread runtime

CHANGELOG.md, Cargo.toml, secio/Cargo.toml, src/service.rs
=> chore: bump to 0.2.2

CHANGELOG.md, Cargo.toml, src/context.rs, src/service.rs, src/substream.rs
Record pending data size in SessionContext.
**Potential use case**:
- Prevent user level push too much data to certain session
=> feat: Record pending data size in SessionContext

src/builder.rs, src/service.rs, src/session.rs
There is a wrong output in listen error
=> fix: fix listen error address mistake

protocols/discovery/src/substream.rs
Only public ip and "0.0.0.0" can publish their discovered address
=> chore: only public ip and "0.0.0.0" can publish their discovered address

yamux/src/session.rs
Fix yamux possible security issues on malicious attack
=> fix: Fix yamux possible security issues on malicious attack

Makefile, protocols/discovery/examples/disc.rs, protocols/identify/examples/id.rs, protocols/ping/examples/ping.rs, protocols/ping/src/lib.rs, yamux/src/session.rs
1. Fix yamux loop forever when keepalive is disabled
2. Fix ping flatbuffer encode function panic
3. fmt on protocols
=> fix: fix some bugs

Cargo.toml, protocols/discovery/Cargo.toml, protocols/discovery/examples/disc.rs, protocols/discovery/src/lib.rs, protocols/discovery/src/substream.rs, protocols/identify/Cargo.toml, protocols/identify/examples/id.rs, protocols/identify/src/lib.rs, protocols/ping/Cargo.toml, secio/Cargo.toml
1. disable discovery publish unreachable ip
2. add test mode to discovery and identify protocol, allow publish any ip
=> Add debug mode

CHANGELOG.md, Cargo.toml, protocols/discovery/Cargo.toml, protocols/discovery/src/substream.rs, protocols/identify/Cargo.toml, protocols/ping/Cargo.toml, secio/Cargo.toml
=> chore: bump to 0.2.5

src/error.rs, src/protocol_handle_stream.rs, src/service.rs, src/session.rs, src/substream.rs
=> feat: change panic report road

src/lib.rs, src/service.rs, yamux/src/error.rs, yamux/src/frame.rs, yamux/src/session.rs, yamux/src/stream.rs
=> fix: fix potential overflow

src/session.rs
=> fix: fix handshake attack

CHANGELOG.md, Cargo.toml, README.md, protocols/discovery/Cargo.toml, protocols/identify/Cargo.toml, protocols/ping/Cargo.toml, src/session.rs, yamux/Cargo.toml, yamux/src/stream.rs
=> chore: bump to 0.2.6

src/builder.rs, src/service.rs, src/service/config.rs, src/session.rs, src/substream.rs, yamux/src/config.rs
=> refactor: remove useless field on yamux

secio/src/crypto/openssl_impl.rs, secio/src/crypto/ring_impl.rs
=> fix: fix overflow on be attacked

src/error.rs, src/protocol_handle_stream.rs, src/service.rs
Next pr will release 0.3.0 alpha 2
=> chore: merge error info

CHANGELOG.md, Cargo.toml, secio/Cargo.toml, yamux/Cargo.toml
=> chore: bump to 0.3.0 alpha2

azure-pipelines.yml, src/service/future_task.rs, src/substream.rs, windows-dependencies.yml, yamux/src/stream.rs
Related pr: #213,  The legacy of that PR. 
Under high pressure, it may cause resources to increase faster than they are released
=> fix: Remove all internal loop restrictions.

src/session.rs
Remove unwanted state analysis
=> perf: Replace unsplit with assignment.

azure-pipelines.yml, tests/test_priority.rs
=> test: test on win

CHANGELOG.md, Cargo.toml, README.md, docs/introduction_en.md, docs/introduction_zh.md, secio/Cargo.toml, yamux/Cargo.toml
=> chore: bump to 0.3.0 alph4

CHANGELOG.md, Cargo.toml, README.md, secio/Cargo.toml, src/service/config.rs, yamux/Cargo.toml
=> chore: bump to 0.3.0 alpha5

src/builder.rs, src/context.rs, src/service.rs, src/service/control.rs, src/session.rs, src/substream.rs
1. Remove some unnecessary data
2. Remove some unnecessary abstractions
3. Remove some unnecessary memory allocation
=> chore: small improve

Cargo.toml, src/channel/bound.rs, src/channel/mod.rs, src/channel/queue.rs, src/channel/sink_impl.rs, src/channel/tests/channel.rs, src/channel/tests/mod.rs, src/channel/tests/mpsc.rs, src/channel/tests/mpsc_close.rs, src/channel/tests/mpsc_priority.rs, src/channel/unbound.rs, src/context.rs, src/lib.rs, src/service.rs, src/service/control.rs, src/service/event.rs, src/session.rs, src/substream.rs
=> feat: Replace priority channel

secio/src/codec/secure_stream.rs, src/session.rs, src/substream.rs
1. rename
2. secio import
dependence #244
=> chroe: Simple modify

yamux/src/session.rs
it will case mem leak on open lots of stream
=> fix: Fix yamux leak mem

secio/src/codec/secure_stream.rs
should use poll to implement the async function, but cannot use the async function to implement poll
Each call to async actually regenerates a temporary future. If the future is pending, it does not save the pending state, but simply drop it. This is incorrect behavior
example:
```rust
async fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
let len = self.socket.write(buf).await?; // ready here
self.socket.flush().await?; // pending here, but this buf is already write to inner socket, it will cause the caller to think that the send was not successful, and try to send again
ok(len)
}
fn poll_write(mut self: Pin<&mut Self>, cx: &mut Context<'_>, buf: &[u8]) -> Poll<io::Result<usize>> {
let task = pin_mut!(self.write(buf));
task.poll(cx)
}
```
right way:
don't use async, manage state by …
=> fix: don't use async to impl poll function, it's wrong way

src/channel/mod.rs, src/channel/sink_impl.rs, src/channel/tests/channel.rs, src/channel/tests/mpsc_priority.rs, src/channel/unbound.rs, src/service/control.rs, src/session.rs, src/substream.rs
1. impl quick send async
2. use substream as a compound word
dependence #247
=> feat: Impl quick send async

yamux/src/session.rs
It is very expensive to call the acquisition time every time a message is sent and received. At the same time, such an operation does not make any sense when the ping message exists, so I decided to remove them
=> perf: reduce time syscall

yamux/src/stream.rs
Because `AsyncWrite + AsyncRead` has Implemented the read-write separation interface `split`. It means the context of reader and writer may be inconsistent. In the original implementation, the writing method used for wake writeable under certain circumstances may lead to the consequence that the write side is not notified, but the read side is notified.
Therefore, the waker on the write side needs to be saved to correctly implement wake writeable
=> fix: cache writeable waker to make the notification flow clearer

src/channel/bound.rs, src/channel/sink_impl.rs, src/channel/tests/mpsc.rs, src/channel/tests/mpsc_close.rs, src/channel/tests/mpsc_priority.rs, src/channel/unbound.rs, src/context.rs, src/service.rs, src/service/control.rs
1. Use atomic bool to avoid mutable API
2. Replace unbound channel with a bound channel
3. Add service control async API
=> feat: Change channel api to immutable

CHANGELOG.md, README.md, secio/Cargo.toml, tentacle/Cargo.toml, tentacle/README.md, yamux/Cargo.toml
=> chore: bump to 0.3.3

tentacle/src/context.rs, tentacle/src/service.rs, tentacle/src/service/control.rs
enable listen function on wasm32 but don't support
=> chore: enable listen function on wasm32 but don't support

tentacle/src/substream.rs
=> fix: unified substream error output

tentacle/src/builder.rs, tentacle/src/context.rs, tentacle/src/service.rs, tentacle/src/service/config.rs, tentacle/src/service/event.rs, tentacle/src/session.rs, tentacle/src/substream.rs, tentacle/tests/test_protocol_open_close_on_spawn.rs
change blocking session detection
=> fix: change blocking session detection

README.md, secio/src/codec/secure_stream.rs, tentacle/Cargo.toml, tentacle/README.md, tentacle/examples/simple.rs, tentacle/src/context.rs, tentacle/src/lib.rs, tentacle/src/service.rs, tentacle/src/session.rs, tentacle/src/substream.rs, yamux/src/session.rs, yamux/src/stream.rs
after #288 
1. Remove the log output of some hot codes
2. Add some documents
=> docs: Add doc

CHANGELOG.md, secio/Cargo.toml, tentacle/Cargo.toml, tentacle/src/runtime/async_runtime.rs, tentacle/src/runtime/mod.rs, tentacle/src/transports/browser.rs, tentacle/src/transports/ws.rs, yamux/Cargo.toml, yamux/src/session.rs
ref https://github.com/driftluo/tentacle/pull/26
=> chore: bump to 0.3.5

Makefile, tentacle/Cargo.toml, tentacle/src/channel/bound.rs, tentacle/src/channel/tests/mpsc.rs, tentacle/src/lib.rs, tentacle/src/lock/mod.rs, tentacle/src/lock/native.rs
Introduce `parking_lot` to tentacle
=> feat: add parking lot compatable api

tentacle/src/service/future_task.rs, tentacle/src/transports/browser.rs, tentacle/src/transports/mod.rs, tentacle/src/transports/tcp.rs, tentacle/src/transports/ws.rs
clean code with a generic type, I hope the existence type can be used as soon as possible
=> refact: use generic type instead of lots of specific type

multiaddr/src/protocol.rs, tentacle/Cargo.toml, tentacle/src/service.rs, tentacle/src/transports/memory.rs, tentacle/src/transports/mod.rs, tentacle/src/utils/dns.rs, tentacle/tests/test_priority.rs
Support use memory multiaddr to test, please review #316 #317 first
=> feat: Support memory

.github/workflows/tentacle_yamux_throughput.yaml, tentacle_yamux_throughput/services/throughput_client_20.service, tentacle_yamux_throughput/services/throughput_client_2000.service, tentacle_yamux_throughput/services/throughput_server.service, tentacle_yamux_throughput/statistics.py
Migrate Tentacle yamux throughput from jenkins to workflow.
TODO:
=> Tentacle yamux throughput

.github/workflows/tentacle_yamux_throughput.yaml
=> fix tentacle CI failed

tentacle/Cargo.toml, tentacle/src/builder.rs, tentacle/src/runtime/async_runtime.rs, tentacle/src/runtime/tokio_runtime.rs, tentacle/src/service.rs, tentacle/src/service/config.rs, tentacle/src/transports/mod.rs, tentacle/src/transports/tcp.rs, tentacle/src/transports/tls.rs, tentacle/src/transports/ws.rs
The configuration behavior of TCP socket is completely abstracted into a user function behavior, allowing users to configure the attributes of TCP socket to the maximum extent
=> feat: enable user config tcp socket

CHANGELOG.md, tentacle/Cargo.toml, tentacle/src/builder.rs, tentacle/src/service.rs, tentacle/src/service/config.rs, tentacle/src/service/future_task.rs, tentacle/src/session.rs
will publish new pre-release on this pr
=> feat: channel bound buffer with config

tentacle/Cargo.toml
This reduces compile times slightly.
=> Upgrade nix to 0.24.1, limit features

CHANGELOG.md, tentacle/Cargo.toml, tentacle/src/runtime/generic_timer.rs, tentacle/src/runtime/tokio_runtime.rs
Considering the behavioral consistency of interval, and to better align with popular community libraries, we will provide two initialization methods and behavior patterns identical to tokio.
=> chore: bump to 0.6.4

.github/workflows/release.yaml, multiaddr/Cargo.toml
=> test: fix release action

.github/workflows/release.yaml
https://github.com/nervosnetwork/tentacle/actions/runs/12117475793/job/33779983052
=> ci: ignore already publish error by cargo

tentacle/src/service.rs, tentacle/tests/test_dial_unsupported_order.rs
fix a bug on an unsupported protocol
=> fix: bug on unsupported protocol

tentacle/Cargo.toml, tentacle/src/transports/browser.rs, tentacle/src/transports/ws.rs
=> feat: wasm support wss

CHANGELOG.md, yamux/Cargo.toml, yamux/src/stream.rs
I don't know why, but the writing here has not been updated to reflect the review comments in #400. This PR will readjust the writing and publish it. (It's not a question of correctness, it's just a question of how to write it.)
=> chore: rollback to better code

tentacle/src/service.rs, tentacle/src/service/control.rs, tentacle/src/service/event.rs
This feature is inspired by NAT traversal functionality. The built-in implementation of this feature within the framework is unstable, and it isn't easy to meet traversal requirements accurately. At this point, it is necessary to provide an interface for Tentacle to receive user-provided pre-built streaming connections and then build the entire protocol stack of Tentacle on top of that.
=> feat: support session init from user

Makefile, secio/Cargo.toml, secio/src/handshake/procedure.rs, secio/src/lib.rs, simple_wasm/package.json, tentacle/Cargo.toml, tentacle/src/builder.rs, tentacle/src/runtime/tokio_runtime/mod.rs, yamux/benches/bench.rs
Maybe the last change before the bump version
=> feat: small change on api

.github/workflows/release.yaml, CHANGELOG.md, tentacle/Cargo.toml, tentacle/src/service.rs
1. Change to trusted release
2. Add peerid filter before dial
=> change to trusted release and add peerid filter before dial
