nervosnetwork/tentacle

discovery/src/lib.rs
discovery/src/message.rs
discovery/src/substream.rs
examples/disc.rs
src/service.rs
src/session.rs

The previous announce is the broadcast client's random address. Now it needs to confirm it as the listening address first, otherwise, it will not broadcast.

Discovery announce listen address

---

Cargo.toml
discovery/src/addr.rs
discovery/src/lib.rs
discovery/src/substream.rs
examples/disc.rs
examples/simple.rs
src/lib.rs
src/service.rs
src/session.rs

In order to support multiple protocols, it is necessary to replace the socket address with `multiaddr`.
The core implementation of `multiaddr` is to parse the string into the specified format of the bytes storage, we do not need to re-implement this library again
The two existing crate implementations can be said to be very similar, and `cid` has a known unresolved bug, so the version of libp2p implementation is chosen.
Discovery may need to rethink the implementation of the store, because the Rawaddr structure should be deleted.
Currently, we only support TCP/IP, multi-protocol support, consider again after stabilization.

Replace socket address with multiaddr

---

.travis.yml
Cargo.toml
bench/Cargo.toml
bench/README.md
bench/src/lib.rs
bench/src/main.rs
benches/bench.rs
yamux/Cargo.toml

Add a bench for the p2p framework.
Since criterion bench is stuck in the test of MB level data, I will write the test as a crate separately. The test results may not be very accurate, but it is already a relatively acceptable solution.
Pause is because of a `yamux` bug, fix on (#26) 
`yamux` bump to 0.1.2

Add a bench for p2p framework

---

Cargo.toml
src/context.rs
src/service.rs
src/session.rs
src/substream.rs

Report open proto failed

---

bench/src/main.rs
examples/disc.rs
examples/simple.rs
ping/src/lib.rs
src/builder.rs
src/service.rs
src/session.rs
src/substream.rs
src/traits.rs
tests/test_dial.rs
tests/test_disconnect.rs
tests/test_kill.rs
tests/test_peer_id.rs

Currently only supports all protocols sharing a codec, this PR is to open this limit, so that different protocols can have different codec

Support multi-codec

---

src/protocol_handle_stream.rs
src/service.rs
src/service/event.rs
src/traits.rs

Support handle customize `poll`

Support handle customize poll

---

bench/src/main.rs
examples/disc.rs
examples/ping.rs
examples/simple.rs
src/builder.rs
src/service.rs
src/service/config.rs
tests/test_dial.rs
tests/test_disconnect.rs
tests/test_kill.rs
tests/test_peer_id.rs

Use FnOnce to define service protocol

Use FnOnce to define service protocol

---

Cargo.toml
README.md
src/utils/dns.rs

We have modified a lot of APIs for friendliness and functionality, and it’s time to release the 0.2 alpha version.
Some adjustments may be made later, depending on the situation

bump to 0.2.0-alpha.1

---

src/utils.rs
src/utils/dns.rs

Originally, this pr will add websocket protocol support, but I gave up on this plan.
Why stop:
1. Currently, our demand for WebSocket is not strong
2. [ws](https://crates.io/crates/ws) is based on [mio](https://crates.io/crates/mio) development, system independence, if we want to integrate, it means that we need `mio` and `tokio` (bottom `mio`) two sets of runtime to run at the same time, this program does not look good
3. [websocket](https://crates.io/crates/websocket) is indeed a library in the `tokio` ecosystem, which is relatively easy to integrate. However, it also has problems, httparse has not started working, relying on hyper 0.10. [ref1](https://github.com/websockets-rs/rust-websocket/issues/132)/[ref2](https://github.com/websockets-rs/rust-websocket/issues/192)
For the above …

Stop ws support plan

---

src/protocol_handle_stream.rs
src/traits.rs

The reason we use trait object now is that the `impl trait` implementation is incomplete and cannot be used in scenarios other than function. 
When anonymous generics can be widely used in Fn / Trait Fn, generics can be used directly, so we can use generics to define structures in advance.

Use generic

---

src/builder.rs
src/protocol_select/mod.rs
src/service/config.rs
src/session.rs

Allow users to customize the version select procedure

feat: Allow users to customize the version select procedure

---

bench/src/main.rs
examples/disc.rs
examples/id.rs
examples/ping.rs
examples/simple.rs
src/builder.rs
src/lib.rs
src/service.rs
tests/test_close.rs
tests/test_dial.rs
tests/test_disconnect.rs
tests/test_kill.rs
tests/test_peer_id.rs

Use the type system to solve possible wrong writing problems

chore: new type id

---

Cargo.toml
protocols/discovery/Cargo.toml
protocols/identify/Cargo.toml
protocols/ping/Cargo.toml
secio/Cargo.toml
yamux/Cargo.toml

It’s been a long time since the last release, and we have a lot of changes and fixes. It’s time to release a new version.
This version is now infinitely close to the official release of 0.2.0, I hope there will be no big changes in the future.

chore: release 0.2-alpha.2

---

Cargo.toml
protocols/discovery/src/protocol.rs
protocols/identify/src/protocol.rs
src/service.rs
src/transports/mod.rs
src/transports/tcp.rs
src/utils.rs
src/utils/dns.rs
tests/test_peer_id.rs

1. Upgrade `multi-address`
2. `multi-address` has break change, we may publish a new version for all protocol and `tentacle`(wait for 0.2.0 ?)

chore: upgrade multi-address

---

Cargo.toml
protocols/discovery/Cargo.toml
protocols/identify/Cargo.toml
protocols/ping/Cargo.toml
secio/Cargo.toml
secio/src/codec/secure_stream.rs
src/service.rs
src/session.rs
src/substream.rs
yamux/Cargo.toml
yamux/src/session.rs

Why use `delay` instead of `notify`?
In fact, on machines that can use multi-core normally, there is almost no problem with the `notify` behavior,
and even the efficiency will be higher.
However, if you are on a single-core bully machine, `notify` may have a very amazing starvation behavior.
Under a single-core machine, `notify` may fall into the loop of infinitely preemptive CPU, causing starvation.

fix: on single-core machine, cpu problem

---

src/service/future_task.rs

Before oneshot sender drop, notify receiver drop

fix: oneshot sender drop

---

tests/test_block_send_session.rs

Because travis CI's resource limitation make this test hard to pass.

test: split test_block_send tests

---

Cargo.toml
README.md
protocols/discovery/Cargo.toml
protocols/identify/Cargo.toml
protocols/ping/Cargo.toml
src/builder.rs
src/service.rs
src/service/config.rs
src/session.rs
src/substream.rs
tests/test_before_function.rs
tests/test_block_send.rs
tests/test_block_send_session.rs

Currently, all the handles on the framework are after handles. If you want to use the before operation on the upper layer, it will be very tricky and difficult to maintain.
Just like you want to add a compressed feature to some of the upper layers of the protocol.  The current way of coding can only be as shown in https://github.com/nervosnetwork/ckb/pull/859.
The p2p framework is very different from the web framework in that there is a need for broadcasting. If the function of compressing messages is done in the codec, it will waste a lot of CPU time, because the same message will increase the compression time as the number of connections grows.
We need a unified way of handling broadcast messages, not exactly the same as codec, just like global preprocessing. This pr adds two …

feat: add before handle

---

secio/Cargo.toml
secio/benches/bench.rs
secio/src/codec/secure_stream.rs
src/protocol_handle_stream.rs
src/service.rs

Use blocking thread to avoid the problem that the reactor is not timely
I read some of the source code of `tokio`, repaired the behavior of the thread that we encrypted and decrypted, and also encapsulated the user interface. 
After passing the test, there was no obvious performance degradation.

chore: Use blocking thread

---

secio/Cargo.toml
secio/src/exchange.rs
secio/src/handshake/procedure.rs

> Users of ring should always use the latest released version, and users should upgrade to the latest released version as soon as it is released
ring only fixes and updates on the latest code. Maybe we need to pay attention to the status of the ring library.

chore: upgrade cryptography library, bump to 0.1.9

---

src/service.rs
src/session.rs
src/substream.rs

In the current implementation, if the user protocol handle panic, the entire service assumes that there is no such protocol and then works "normally".
In the previous version which has a single point performance bottleneck, the user protocol handle panic will shutdown the entire service. But lost this logic in the process of refactoring.
Pretending that the service is "normal" is not a good way to handle it. It makes it difficult for users to find problems with the protocol they are implementing, so I decided to roll back this operation.

revert: handle panic shutdown mechanism

---

CHANGELOG.md
Cargo.toml
README.md
protocols/discovery/Cargo.toml
protocols/identify/Cargo.toml
protocols/ping/Cargo.toml
secio/Cargo.toml
yamux/Cargo.toml

This is probably the last release of the 0.2 version.
The master branch will start to adapt to the `async` syntax later. Good luck for me.
wait for #179
wait for #180 
wait for #184

chore: bump to 0.2.4

---

src/session.rs
src/substream.rs

During the upgrade process, I found that:
1. Session `set_delay` status setting error，may cause an invalid call
2. Substream cache processing is not timely

fix: small fix

---

src/builder.rs
src/service.rs
src/service/config.rs

Tentacle has not previously made any restrictions on the number of transport connections, which may lead to fd attacks. The good news is that the consequence of the fd attack is only that the listening service will be closed, and it will not affect the established connection. But we should fix it.
The fd create on [std::sys::net](https://doc.rust-lang.org/nightly/src/std/sys/unix/net.rs.html#192-223), and it will call by `tokio::tcplistener::poll_accpet`, their calling relationship is as follows:
tokio -> mio -> std net -> std sys common -> std sys net -> std sys fd -> syscall

fix: add transport connection number limit on listener

---

Cargo.toml
src/upnp/windows.rs

Use winapi's heap* series of interfaces to allocate and clean up memory on win, thereby removing `libc` dependencies

[ᚬuse-async-await] feat: remove libc dep on windows

---

secio/src/codec/secure_stream.rs
src/protocol_handle_stream.rs
src/service.rs
src/session.rs
src/substream.rs
yamux/Cargo.toml
yamux/examples/throughput_test.rs
yamux/src/session.rs

There is a throughput issue. Although it was not warned in the current project, it is indeed a bug.
This bug is reported by @biluohc, thanks for his work, and his test data is:
**When sub-stream opens more than 64, the throughput plummets**
In this PR, I brought a test case that can be used to detect the effect. Of course, I will also post the test data here.
The number means how many sub-stream the test open
On my machine:
before:
```shell
$ env RUST_LOG=info ../target/release/examples/throughput_test 60
[2020-03-17T09:34:41Z INFO  throughput_test] 10 secs req 2199349, resp 2199382; 219934.9 req/s, 19.7 MiB/s; 219938.2 resp/s 19.7 MiB/s
[2020-03-17T09:34:51Z INFO  throughput_test] 10 secs req 2084170, resp 2084170; 208417 req/s, 18.7 MiB/s; 208417 resp/s 18.7 MiB/s
[2020-03-17T09:35:01Z …
```

fix: Fix throughput issues caused by code limit

---

src/service/future_task.rs

`oneshot::Sender.send()` return a `Future`, we must use `.await` to poll it.

fix: Fix FutureTask signals memory leak

---

src/protocol_handle_stream.rs
src/service.rs
src/session.rs
src/substream.rs
src/traits.rs
tests/test_session_handle_open.rs
tests/test_session_protocol_open_close.rs

This is a long-established bug that only affects the manual opening of the user's protocol at the session-level.
There's a logical confusion here, the handle doesn't need to be open every time it's open, because the session is already resident when it's open. The handle does not need to be removed when the protocol is closed alone, but only when the session is closed.
Now, with the addition of a test case here.

fix: fix session proto open/close by user part

---

Cargo.toml
bench/Cargo.toml
secio/Cargo.toml
secio/src/codec/secure_stream.rs
src/traits.rs
yamux/Cargo.toml
yamux/src/frame.rs

tokio-util:
1. api break change
2. Use advance over split_to when data is not needed

chore: upgrade tokio util

---

src/builder.rs
src/protocol_handle_stream.rs
src/service.rs
src/service/config.rs

Previously, `block_in_place` was used by default to perform user behavior, just for convenience, but in practice, most functions do not require this operation, now a flag is added to let the user control this behavior.
There is a lot of `block_in_place` behaviors, such as judging and setting status, opening new threads, etc. These are additional overheads, and if the user can control whether this behavior is needed or not, it is a big improvement to overall performance.
I used a simple demo to test the difference between the two:
```rust
use criterion::{criterion_group, criterion_main, Bencher, Criterion};
use std::collections::HashMap;
fn blocking(rt: &mut tokio::runtime::Runtime, hash_time: usize) {
rt.block_on(async move {
let mut handles = Vec::new();
for _ in 0..256 {
let handle = …
```

feat: use flag to control how to use `block_in_place`

---

secio/src/codec/secure_stream.rs
secio/src/codec/stream_handle.rs
secio/src/handshake/handshake_context.rs

Reduce a useless copy of secio during transmission
I write a bench code:
```rust
use criterion::{criterion_group, criterion_main, Bencher, Criterion};
use bytes::{BytesMut, Bytes, Buf};
fn bytesmut_decode_test(data: Vec<u8>) {
let mut a = BytesMut::from(data.as_slice());
a.advance(16);
let a  = a.split_to(a.len()- 1);
}
fn vec_decode_test(mut data: Vec<u8>) {
let mut a = data.split_off(16);
let a = a.split_off(a.len()- 1);
}
fn vec_decode_test_drain(mut data: Vec<u8>) {
data.drain(..16);
data.drain(..data.len());
}
fn bytes_encode_test(data: Vec<u8>) {
let a = BytesMut::from(data.as_slice());
let a  = a.freeze();
}
fn vec_encode_test(data: Vec<u8>) {
let a  = Bytes::from(data);
}
fn bench_encode_test(bench: &mut Bencher, bytes:bool, data: Vec<u8>) {
bench.iter(|| {
if bytes { …
```

perf: reduce one copy behavior during transmission

---

Cargo.toml
secio/src/handshake/procedure.rs
src/context.rs
src/error.rs
src/protocol_handle_stream.rs
src/service.rs
src/service/control.rs
src/service/event.rs
src/session.rs
src/substream.rs
src/transports/mod.rs
src/transports/tcp.rs
tests/test_dial.rs
tests/test_peer_id.rs

A big `Error` enum is used in previous code, which introduces difficulties in error handling for lib user: he need to know that only some of the error enum variables will need to be dealt with under different circumstances: for example, `ServiceError::ProtocolHandleError` only contains `ProtoHandleAbnormallyClosed` and `ProtoHandleBlock` .
This PR split it to serval small `ErrorKind` enums and refactored some internal code to use a smaller scoped error.

[BREAK CHANGE] refactor: split the big `Error` enum into a several small `ErrorKind` enums

---

secio/README.md
secio/src/handshake/handshake_struct.rs

If we want to get the peerid information through the public key, the current API cannot complete this task

feat: parse slice to pubkey

---

secio/src/codec/secure_stream.rs
src/service.rs
src/service/helper.rs
src/session.rs

1. Split listener from Service
2. Use `foreach` instead of `boxed` to reduce box cost
3. Unified handshake success event stream to `Dyn trait`
4. Remove `dialstart` event, it can directly enter the handshake process and does not require one more communication
5. Unified handshake process as a single abstraction
This pr depends on the previous pr and  #237 needs to be reviewed first

Split listener

---

src/service.rs
src/session.rs
tests/test_block_future_task.rs
tests/test_close.rs
tests/test_dial.rs

1. Remove the service record of protocols on and off
2. Migration of session protocol handle records to session management
3. When the Event mode is disabled, cancel the ProtocolOpen and ProtocolClose events
Review the other #237 #238  two PRs first

feat: Remove sevice's awareness of protocol

---

secio/src/codec/secure_stream.rs
src/channel/unbound.rs
src/context.rs
src/service.rs
src/service/control.rs
src/session.rs
src/substream.rs
yamux/src/session.rs
yamux/src/stream.rs

A long, long time ago, because of some latency issues, and without getting into the details of why, we added the `set_delay` temporary solution to the problem, which has now been found by reading the source code and implementing the async channel. It's time to remove the side-effects `set_delay`
In an asynchronous environment, any operation that needs to wait asynchronously will be notified after the other end is ready. The key is how to set the waker correctly to let the peer(resource side) know that this method has not been found before, so a method with side effects is used.
run `example/block_send.rs` time:
before:
after:

feat: Remove set delay

---

examples/block_send.rs
src/protocol_handle_stream.rs
src/service.rs
src/service/future_task.rs
src/session.rs
src/substream.rs
src/traits.rs
yamux/src/session.rs

Rewrite the stream poll implementation, the original implementation is likely to miss the notify message.
There are several ways to write stream join:
```rust
fn poll_next() -> Poll<Option<()>> {
loop {
stream1.poll()
pending break
}
loop {
stream2.poll()
pending break
}
Poll::Pending
}
```
In this way of writing, when stream2 polls, stream1 is already ready, and notifications will be missed, causing the delay of stream1.
```rust
fn poll_next() -> Poll<Option<()>> {
let mut is_pending = stream1.poll().is_pending();
is_pending &= stream2.poll().is_pending();
if is_pending {
Poll::Pending
} else {
Poll::Ready(Some(()))
}
}
```
This approach minimizes the number of appeals.
By the way, the futures macro `select!` use the same way to poll the stream join, but it will box all the streams and …

refactor: rewrite stream poll to try to avoid delay in stream join

---

src/service.rs
src/session.rs
src/substream.rs
yamux/src/session.rs

Considering that what we need is hierarchical ordering instead of global ordering, the original buffer strategy guarantees global ordering, and there will be additional consumption. For example, the buffers must be traversed all the time, and after changing the order to the hierarchy, this Side effects will disappear
dependence #243

refacor: Rewrite buffer cache

---

src/service.rs
src/session.rs
tests/test_session_protocol_open_close.rs
yamux/src/control.rs
yamux/src/lib.rs
yamux/src/session.rs
yamux/src/stream.rs

The previous way `yamux` was written forced the user to wrap the session in their own upper-tier application, which was not a good experience and was a historical decision. When async was unstable, control implementations were not as practical, but now control can be abstracted out.
The upper wrapper `yamux` session affects the efficiency of upper-level data delivery, and a lot of time is taken up by the lower level sending and receiving. The better way to handle it is to spawn out.
At the same time, when the stream is unexpectedly disconnected, an RST message should be sent to the counterpart, the current implementation of the drop.

feat: Add control on yamux

---

yamux/src/frame.rs
yamux/src/session.rs
yamux/src/stream.rs

`yamux` has some discrepancies in exception handling that need to be fixed.
read data error： flag error or data > max length
https://github.com/hashicorp/yamux/blob/7221087c3d281fda5f794e28c2ea4c6e4d5c4558/session.go#L516
https://github.com/hashicorp/yamux/blob/7221087c3d281fda5f794e28c2ea4c6e4d5c4558/session.go#L526
open stream with an existing stream id
https://github.com/hashicorp/yamux/blob/7221087c3d281fda5f794e28c2ea4c6e4d5c4558/session.go#L600
These fixes do not have compatibility issues and reduce the tolerance for anomalous behavior
dependence #246

fix: Add send go away

---

src/buffer.rs
src/context.rs
src/lib.rs
src/service.rs
src/session.rs
src/substream.rs

Use a unified buffer abstract structure to manage the entire tentacle buffer to facilitate testing
dependence #248

feat: Rewrite buffer cache

---

yamux/examples/yamux_simple.rs
yamux/src/session.rs
yamux/src/stream.rs

fix #259
When the session is closed, all streams need to be set to `RemoteClosed`

fix: fix stream stuck after the underlying connection is closed

---

Cargo.toml
Makefile
multiaddr/Cargo.toml
multiaddr/src/protocol.rs
src/service.rs
src/transports/mod.rs
src/transports/ws.rs
src/utils/dns.rs

Add support for WebSocket, now web applications can communicate directly with each other.

feat: support websocket transport

---

Cargo.toml
src/builder.rs
src/channel/mod.rs
src/error.rs
src/service.rs
src/service/config.rs
src/session.rs
src/transports/mod.rs
src/transports/tcp.rs
src/transports/ws.rs

Before this PR, the NAT penetration function that can be used is only UPnP routing registration, but it has some limitations. It can only pray that the node is behind a layer of NAT. If there are multiple layers of NAT, a single UPnP cannot public listen port to the public network. 
Multi-layer NAT penetration is a difficult and uncertain thing, the challenge is to get the TCP connect signal to be sent to the correct listening port on the intranet, so the problem becomes how to establish a mapping of intranet listening to public ports under multi-layer NAT.
As we can see, there is a protocol called [STUN](https://tools.ietf.org/html/rfc5389), which, at its core, allows an intranet node to know its extranet mapped address and port through the STUN server, and to keep that channel …

feat: Enable reuse port

---

yamux/Cargo.toml
yamux/src/session.rs
yamux/src/stream.rs

make yamux independent of the specific runtime

feat: make yamux independent of the specific runtime

---

CHANGELOG.md
tentacle/Cargo.toml
yamux/Cargo.toml

The next PRs are all related to wasm, we can package a version of the stable feature first

chore: bump to 0.3.2

---

fuzz/fuzz_targets/secio/crypto/decrypt_cipher.rs
fuzz/fuzz_targets/secio/crypto/encrypt_cipher.rs
secio/Cargo.toml
secio/benches/bench.rs
secio/src/codec/secure_stream.rs
secio/src/crypto/cipher.rs
secio/src/crypto/mod.rs
secio/src/crypto/openssl_impl.rs
secio/src/crypto/ring_impl.rs
secio/src/exchange.rs
secio/src/handshake/procedure.rs
secio/src/support.rs

review #269 first
Why do this？
Because only in this way can the next step of development be carried out when the review speed is extremely slow
---
1. remove aes ctr support
2. add x25519 support

feat: remove aesctr, add x25519 support

---

tentacle/src/runtime/async_runtime.rs
tentacle/src/runtime/mod.rs
tentacle/src/runtime/tokio_runtime.rs
tentacle/src/transports/mod.rs

review #273 first
1. `async-std` pin async poll on accept won't wake up on Windows, but work on Linux
2. due to https://github.com/tokio-rs/tokio/issues/3030, use compatible fn on Windows

fix: Fix win compatible

---

yamux/src/session.rs

The throughput problem reappeared because of this commit https://github.com/nervosnetwork/tentacle/commit/1ea53e989c8a33313ccda69f093f23b35948d3d0
test case: https://github.com/nervosnetwork/tentacle/pull/213
Although in actual production there will be no sub-substreams above 100 levels, this is indeed a problem. After regression testing, the current code will show a significant throughput drop when it is around 800.
perf `./target/release/examples/throughput_test 800`
master branch: CPU consumption of `distribute_to_substream` function accounts for more than 50%
patch branch: CPU consumption problem of `distribute_to_substream` function cannot be clearly observed, about 2.5%
This is a classic continuous memory and segmented memory overhead problem. In a test scenario under full pressure, …

revert: revert yamux buffer

---

bench/src/lib.rs
tentacle/src/service.rs
tentacle/src/session.rs

The usage of `fold` is a little ugly.

chore: replace unnecessary fold by `.map(..).sum()`

---

Makefile
tentacle/Cargo.toml
tentacle/examples/simple_using_spawn.rs
tentacle/examples/use_spawn.rs
tentacle/src/builder.rs
tentacle/src/lib.rs
tentacle/src/runtime/async_runtime.rs
tentacle/src/runtime/mod.rs
tentacle/src/service.rs
tentacle/src/service/config.rs
tentacle/src/session.rs
tentacle/src/substream.rs
tentacle/src/traits.rs
tentacle/tests/test_protocol_open_close_on_spawn.rs
yamux/src/stream.rs

In order to allow users to achieve a fully streamed reading and writing experience, and to bypass the problem of the async trait.
I add an interface that is mutually exclusive with the previous callback model. It can get all the information required by the protocol, suitable for async environment

feat: add protocol spawn feature

---

secio/src/codec/secure_stream.rs
tentacle/src/channel/queue.rs
tentacle/src/substream.rs
tentacle/tests/test_block_send.rs
tentacle/tests/test_block_send_session.rs
yamux/src/session.rs
yamux/src/stream.rs

1. sink `start_send` just set data to buffer, `flush` will try to write data to inner io
2. Remove write buffer on yamux stream, it will cause context confusion, and let the data be copied once more
3. yamux stream read must break on having read something
4. yamux control message send by unbound channel
5. secio after confirming that it can be sent, encrypt the data
codec write buffer left:
https://github.com/nervosnetwork/tentacle/blob/fix-message-delay/tentacle/src/substream.rs#L427
yamux read buffer left:
https://github.com/nervosnetwork/tentacle/blob/fix-message-delay/yamux/src/stream.rs#L302

fix: fix some msg left on buffer

---

secio/src/handshake/procedure.rs
yamux/src/session.rs

ref: #288 
This PR removes the flush command of the stream, because this command and the real message will squeeze each other, and the channel does not need the flush action in the actual sense. This means that the flush operation of the underlying io will be completely executed by the session.
There is no problem originally. Each poll executes a flush, but because the poll has a loop, the flush must be moved into the loop to be completely equivalent to a poll and a flush of other streams.

fix: yamux session flush must once a loop

---

secio/src/codec/secure_stream.rs
secio/src/crypto/mod.rs
secio/src/crypto/ring_impl.rs
yamux/src/stream.rs

in place decrypt on p2p bench
before：
```
After counting 10 cycles, estimated total time spent on task "10mb_benchmark_with_secio" is 2.6936522s                                 
task name: 10mb_benchmark_with_secio                                                                                                   
cycles: 100                                                                                                                            
total cost: 3.628672348s                                                                                                               
average: 36.286723ms                                                                                                                   
median: 45.029141ms …
```

perf: Perf

---

tentacle/src/buffer.rs
yamux/src/session.rs
yamux/src/stream.rs

fix #297 
In the case of strict message order, the introduction of inconsistent queues will cause inconsistent concurrency order
yank 0.2.9-10 yamux

fix: fix random open stream fail

---

yamux/src/session.rs

`Syn` must respond `Ack`, Otherwise it will enter an endless loop of syn ping/pong

fix: fix wrong flag

---

tentacle/Cargo.toml
tentacle/src/channel/bound.rs
tentacle/src/channel/mod.rs
tentacle/src/channel/tests/mpsc_close.rs
tentacle/src/channel/unbound.rs

port from https://github.com/rust-lang/futures-rs/pull/2304

fix: port futures-rs fix on channel

---

yamux/src/session.rs

Rust's asynchronous system is a collaborative model, which means that all Futures should not occupy the executor for a long time. 
There is a risk of preemption when yamux uses a loop. There will be no obvious problems under a single connection. However, when a large number of connections exist, if yamux is occupied for a long time, it will affect the scheduling of the entire task system, especially when the CPU capacity is insufficient. It will become more and more obvious on the machine, the consequence is that the communication speed will be greatly jittered.
What are the problems with occupying the executor for a long time? 
First, it will cause the work-steal trigger to become more frequent
Second, it will affect the drivers triggering 
Generally, Future tasks use executor in the …

chore: dont use loop on yamux

---

tentacle/Cargo.toml
yamux/src/session.rs
yamux/src/stream.rs

1. fix remote does not respond go away
In the current implementation, if the other party does not respond to go away, yamux will wait forever, causing a possible fd attack. Although this is a poorly maintained attack method, during the attack, it must respond to ping/pong messages, otherwise, it will be closed. We cannot be sure whether the remote implementation is fully compliant with the specification. At this time, there must be a shutdown strategy, which is to set a timeout time. When the remote timeout does not respond, the connection will be closed by itself. 
Since yamux needs to be runtime independent, the only thing that can be done here is to instantly replace the ping timer, whether it exists or not, at the same time, due to the inconsistency of timer implementation, it is …

fix: Fix yamux close

---

.travis.yml
tentacle/src/service.rs
tentacle/src/service/config.rs
tentacle/src/service/event.rs

feat: change multi to filter

---

CHANGELOG.md
Makefile
README.md
multiaddr/Cargo.toml
secio/Cargo.toml
tentacle/Cargo.toml
tentacle/README.md
tentacle/src/lib.rs
yamux/Cargo.toml

wait for #318 
This version is to allow users to transition to the tokio 1.0 era and then will begin async trait, which will be a very big break change, so the alpha version will be released first. When the async trait is implemented, the 0.4.0 version will be released.

chore: bump to 0.4.0-alpha1

---

yamux/src/config.rs
yamux/src/frame.rs
yamux/src/session.rs
yamux/src/stream.rs

There are two problems here, which cause yamux to fail to increase the default window normally:
1. From [spec](https://github.com/hashicorp/yamux/blob/0bc27b27de87381b58e35462a8dcbd69040279c1/spec.md#flow-control), stream init window size must be 256kb
2. Codec only needs to judge the size of length when it is of data type, to return in advance 
The above modification does not affect the behavior under the default configuration but affects the user configuration behavior 
**Warng: If you need to adjust the window size, please update all application dependencies in time**

fix: yamux window update bug

---

.gitignore
Makefile
tentacle/src/session.rs
tentacle/src/substream.rs
tentacle/tests/test_dial.rs
tentacle/tests/test_tls_dial.rs

Command to increase statistical test coverage, although it is a bit inaccurate
After `make cov`, an HTML display will be generated in the `tentacle-cov` directory, which can be opened directly through the browser

chore: add cov

---

yamux/src/session.rs

Scheduling logging is high frequency and only useful when debugging p2p schedulers. Most of the time, users don't care about scheduling details. I therefore lower its log-level to `Trace`.

chore: lower loglevel of scheduling logs

---

CHANGELOG.md
tentacle/Cargo.toml
tentacle/src/builder.rs
tentacle/src/context.rs
tentacle/src/runtime/async_runtime.rs
tentacle/src/runtime/tokio_runtime.rs

fix: fix bind twice

---

CHANGELOG.md
bench/Cargo.toml
fuzz/Cargo.toml
secio/Cargo.toml
tentacle/Cargo.toml
tentacle/src/runtime/async_runtime.rs
tentacle/src/upnp/mod.rs
yamux/Cargo.toml
yamux/src/session.rs

ref https://github.com/rust-lang/rust/pull/89926
will publish after merge

fix: instant panic

---

tentacle/src/service.rs
tentacle/src/service/config.rs

ref #305 
After a period of online testing and use, we found that we needed to add back `Multi`
The current methods of sending messages can be divided into two main categories: 
1. sending with a specified id (Single, Multi)
2. send all (All, Filter)
For multicast where the specified object is known, using `Filter` is a costly act and a full traversal of all connected nodes must be performed.
`Filter` is more suitable for behaviors where the specific target is not known, but the sending rules are known, such as [gossip](https://github.com/nervosnetwork/axon/blob/main/core/network/src/outbound/gossip.rs#L166)
Now there is one more problem, do we need to specify `Vec` or the more loose `Box<dyn Iterator<Item = SessionId> + Send + 'static>` as the type of `Multi`？ @TheWaWaR @quake

feat: re-add multi to target session

---

.github/workflows/ci.yaml
CHANGELOG.md
tentacle/Cargo.toml

It looks like this should be the last beta before the official release, and no API change requirements have been found so far

chore: bump to 0.4.0-beta5

---

tentacle/src/runtime/async_runtime.rs
tentacle/src/runtime/tokio_runtime.rs

we introduce tcp config on https://github.com/nervosnetwork/tentacle/pull/339 ，but it remove default feature `reuse_addr` on https://github.com/tokio-rs/mio/blob/master/src/net/tcp/listener.rs#L74, cause some unexpected behavior, so we add  it back now, user can disable it on their own tcp config
ref https://github.com/nervosnetwork/ckb/runs/6985034924?check_suite_focus=true

feat: reuse address by default

---

tentacle/src/builder.rs
tentacle/src/protocol_handle_stream.rs
tentacle/src/runtime/async_runtime.rs
tentacle/src/runtime/budget.rs
tentacle/src/runtime/mod.rs
tentacle/src/runtime/tokio_runtime.rs
tentacle/src/runtime/wasm_runtime.rs
tentacle/src/service.rs
tentacle/src/service/config.rs
tentacle/src/service/future_task.rs
tentacle/src/session.rs
tentacle/src/substream.rs
tentacle/tests/test_uninterrupter_poll.rs

In the process of upgrading the ckb dependency, I encountered the problem that the unit test did not pass after the upgrade, and after spending about two days locating and fixing it, I produced this PR.
First of all, the problem arises when the upgrade process incorrectly implements a trait, which happens with ckb's ping protocol:
```rust
/// Behave like `Stream::poll_next`, but nothing output
/// if ready with Some, it will continue poll immediately
/// if ready with None, it will don't try to call the function again
#[inline]
async fn poll(&mut self, _context: ProtocolContextMutRef<'_>) -> Option<()> {
Some(())
}
```
This implementation causes the future generated by this method to be called uninterruptedly, which is not a big problem when a runtime starts a network, but when multiple …

fix: Fix bug

---

yamux/src/stream.rs

this fixes #360.
- `process_flags`以前会在内部将`LocalClosing`和`Reset`状态转换到`Closed`，阻止`poll_read`观测`Closed`的来源，现在将状态保留了，`drop`部分对应`Reset`的检查也有更新。
- `check_self_state`现在返回一个`Result<Option<Result>>`，表示存在不需要读底层的流就能向用户返回数据的情况（根据约定，对EOF返回一个零长度的读）。
- 以前yamux在一端`shutdown`后，另一方向的流也会出现问题，所以放宽了`poll_read`, `poll_write`等几个函数中的一些flag检查，现在可以在`shutdown`之后继续调用`read`读取数据了。

fix: poll_read: wrong behavior on half close

---

CHANGELOG.md
secio/Cargo.toml
secio/src/handshake/handshake_struct.rs
secio/src/handshake/procedure.rs
secio/src/lib.rs

https://github.com/nervosnetwork/tentacle/pull/366/files#diff-b60df668d0b0edb322e9b7319ada7c4b1b54191095cb3209d741b1e66bc10ad4L143
1. Expose the PublicKey `from_raw_key` api
2. I will yank 0.6.0, because `KeyProvider` has changed
why change `KeyProvider::verify_ecdsa` with self-bound?
If the user wants to combine the two Keys into one enum, user can only write the following implementation, but such an implementation has security issues
```rust
#[derive(Clone)]
enum KeyP<K: KeyProvider> {
Custom(K),
Default(SecioKeyPair),
}
#[async_trait]
impl<K> KeyProvider for KeyP<K>
where
K: KeyProvider,
{
type Error = SecioError;
async fn sign_ecdsa_async<T: AsRef<[u8]> + Send>(
&self,
message: T,
) -> Result<Vec<u8>, Self::Error> {
match self {
KeyP::Custom(k) => …
```

chore: bump secio to 0.6.1

---

tentacle/src/runtime/tokio_runtime.rs

https://github.com/nervosnetwork/tentacle/blob/master/tentacle/src/runtime/generic_timer.rs#L19
generic timer uses `Delay` to implement interval, its behavior is to wake up after the delay time, and then reset the delay. tokio timer `interval` wakes up immediately without delay, we should use `interval_at` to set interval start instant to make them have consistent behavior

fix: Fix interval inconsistent behavior

---

tentacle/Cargo.toml
tentacle/examples/simple.rs
tentacle/src/buffer.rs
tentacle/src/channel/mod.rs
tentacle/src/lock/mod.rs
tentacle/src/runtime/async_runtime.rs
tentacle/src/runtime/budget.rs
tentacle/src/runtime/tokio_runtime.rs
tentacle/src/service.rs
tentacle/src/service/future_task.rs
tentacle/src/transports/browser.rs
tentacle/src/transports/memory.rs
tentacle/src/transports/mod.rs
tentacle/src/transports/tcp.rs
tentacle/src/transports/tcp_base_listen.rs
tentacle/src/transports/tls.rs
tentacle/src/transports/ws.rs
tentacle/src/utils.rs
tentacle/src/utils/dns.rs
tentacle/tests/tcp_upgrade_mod.rs
tentacle/tests/test_session_handle_open.rs
tentacle/tests/test_session_protocol_order.rs
tentacle/tests/test_tls_dial.rs
tentacle/tests/test_tls_reconnect.rs

In the original implementation, TCP/WS/TLS could not be listened on the same port. After this PR, these protocols can be listened on the same port.

feat: enable tcp base protocol listen on same port

---

Makefile
fuzz/Cargo.toml
multiaddr/src/protocol.rs
secio/src/peer_id.rs

The [upstream](https://github.com/multiformats/rust-multihash/commit/ebc4d859db0376dd4bf32552e78cf1d9dd7433d6) has fully encoded the hash code into u64. This PR will follow upstream changes. no break change
fuzz test break by https://github.com/rust-lang/rust/issues/135515

feat: change by upstream

---

multiaddr/Cargo.toml
multiaddr/src/error.rs
multiaddr/src/lib.rs
multiaddr/src/onion_addr.rs
multiaddr/src/protocol.rs
multiaddr/tests/lib.rs
multiaddr/tests/onion.rs

The code changes are copied from https://github.com/multiformats/rust-multiaddr/blob/master/src/onion_addr.rs
(No need to support Onion v2, it has been deprecated: https://support.torproject.org/onionservices/v2-deprecation/)

multiaddr: Support Onion Protocol

---

yamux/Cargo.toml
yamux/benches/bench.rs
yamux/src/stream.rs

#398 use `extend_from_slice` will copy all data twice, this pr use `Vec<BytesMut>` reduces its copy from all data to just one ptr, and  Vec's memory allocation and release do not always work, because `drain` does not reclaim memory, that is, the memory allocation operation here is limited
bench master and this pr:
master branch:
```
Gnuplot not found, using plotters backend
yamux_beach/            time:   [475.10 µs 544.57 µs 618.04 µs]                         
change: [-5.0316% +12.625% +35.408%] (p = 0.20 > 0.05)
No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
4 (4.00%) high mild
```
this pr:
```
Gnuplot not found, using plotters backend
yamux_beach/            time:   [393.64 µs 451.65 µs 514.75 µs]                         
change: [-34.776% -23.230% …
```

perf: perf yamux stream read buf

---

multiaddr/Cargo.toml
secio/Cargo.toml
tentacle/Cargo.toml
yamux/Cargo.toml

This PR use `cargo msrv find --ignore-lockfile` found the MSRV
(`./bench/Cargo.toml` no need to set MSRV.

cargo: set MSRV for tentacle workspace members

---

multiaddr/src/onion_addr.rs
multiaddr/src/protocol.rs
tentacle/Cargo.toml
tentacle/src/builder.rs
tentacle/src/channel/queue.rs
tentacle/src/error.rs
tentacle/src/runtime/mod.rs
tentacle/src/runtime/proxy/mod.rs
tentacle/src/runtime/proxy/socks5.rs
tentacle/src/runtime/proxy/socks5_config.rs
tentacle/src/runtime/tokio_runtime/mod.rs
tentacle/src/service.rs
tentacle/src/service/config.rs
tentacle/src/service/future_task.rs
tentacle/src/transports/mod.rs
tentacle/src/transports/onion.rs
tentacle/src/utils.rs
tentacle/src/utils/dns.rs

This PR introduces and supports Onion3 multiaddr for tentacle-multiaddr and adds `socks5` proxy support for tentacle dialing. It also allows tentacle to connect to a Tor server to reach an onion address.
A breaking change introduced is:
1. Changing 
```rust
pub(crate) type TcpSocketConfig =
Arc<dyn Fn(TcpSocket) -> Result<TcpSocket, std::io::Error> + Send + Sync + 'static>;
```
to:
```rust
pub(crate) type TcpSocketTransformer =
Arc<dyn Fn(TcpSocket) -> Result<TcpSocket, std::io::Error> + Send + Sync + 'static>;
pub(crate) struct TcpSocketConfig {
pub(crate) socket_transformer: TcpSocketTransformer,
pub(crate) proxy_config: Option<ProxyConfig>,
}
```
2. Adding an `Onion` variant to the `TransportType` enum and implementing `OnionTransport`.
3. Allow `runtime::connect` to use a `socks5` …

Support proxy and onion

---

tentacle/Cargo.toml
tentacle/src/runtime/tokio_runtime/mod.rs
tentacle/src/service.rs
tentacle/src/service/helper.rs
tentacle/src/transports/mod.rs

After #382 introduced single-port multi-protocol support, the drop listener does not handle multiple protocols. This PR fixes this issue

fix: listen drop with upgrade mode
